---
- name: Understanding vars
  hosts: all
  become: yes
  # vars:
  #   USRM: playuser
  #   COMM: variable from playbooks
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{USRM}}"
        comment: "{{COMM}}"
      register: userout
    
    - debug:
        var: userout.name
    - debug: 
        var: userout.comment