---
# handlers file for post-install
- name: Restart NTP service on CentOS
  service: 
    name: chronyd
    state: restarted
    enabled: yes
  when: ansible_distribution == "CentOS"
  notify: 
    - Restart NTP service on CentOS

- name: Restart NTP service on Ubuntu
  service: 
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu"